version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    command:
      - cd $CODEBUILD_SRC_DIR
      - echo "Start npm install..."
      - npm install
  build:
    commands:
      - echo "Building Typescript/React code..."
      - npm run build
artifacts:
  files:
    - appspec.yml
    - build/**
    - scripts/**
  discard-paths: yes

cache:
  paths:
    - "/root/.gradle/caches/**/*"
